{
 "title": "EKS Container Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod_name\"}, container)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\",pod=\"$pod_name\"},kubernetes_node)"
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{pod=\"$pod_name\", kubernetes_node=\"$node\"}, pod_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod IP Address",
   "type": "text",
   "description": "IP Address used by the POD.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "content": "<h1><p style=\"text-align: center;\">$pod_ip</p></h1>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Memory Usage (Mb)",
   "type": "singlestat",
   "description": "Amount of RAM used by the selected container. ",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$container\",pod=\"$pod_name\"}) / 1024 / 1000"
    }
   ]
  },
  {
   "title": "Container Status",
   "type": "singlestat",
   "description": "Status of the current container.",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(kube_pod_container_status_running{namespace=\"$namespace\",pod=\"$pod_name\",container=\"$container\"}*1)"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "singlestat",
   "description": "Number of times a pod container has restarted.",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "description": "Container CPU Usage.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"$container\",namespace=\"$namespace\",pod_name=\"$pod_name\"}[5m])) by (container) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Pod Memory Usage.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"$container\",namespace=\"$namespace\",pod_name=\"$pod_name\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}