{
 "title": "EKS Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup=\"$nodegroup\"}, label_kubernetes_io_hostname)"
   },
   {
    "name": "pod_name",
    "query": "label_values(kube_pod_labels,pod)"
   },
   {
    "name": "nodegroup",
    "label": "NodeGroup",
    "query": "label_values(kube_node_labels{kubernetes_namespace=\"ops\"},label_eks_amazonaws_com_nodegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Running Pods",
   "type": "singlestat",
   "description": "Number of running pods.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pod_count{instance=\"${Node:raw}\"}"
    }
   ]
  },
  {
   "title": "Node Pod Usage",
   "type": "gauge",
   "description": "Node Pod Usage.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$Node\"}) / sum(kube_node_status_allocatable_pods{node=\"$Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Number of CPU Cores",
   "type": "singlestat",
   "description": "Number of CPU Cores.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"$Node\"}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "singlestat",
   "description": "Duration of Server Uptime.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "Max(node_time_seconds{kubernetes_node=\"$Node\"} - node_boot_time_seconds{kubernetes_node=\"$Node\"})"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "gauge",
   "description": "Node Disk Usage.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum((node_filesystem_size_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"} - node_filesystem_free_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"}) / node_filesystem_size_bytes{kubernetes_node=\"$Node\",mountpoint=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "description": "Node System Load.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load5{kubernetes_node=\"$Node\"}",
     "legendFormat": "load5"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Node CPU Usage.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{kubernetes_node=\"$Node\",mode=~\"system|irq|softirq\"}[5m])) * 100)",
     "legendFormat": "system"
    },
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{kubernetes_node=\"$Node\",mode=~\"user\"}[5m])) * 100)",
     "legendFormat": "user"
    },
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{kubernetes_node=\"$Node\",mode=~\"iowait\"}[5m])) * 100)",
     "legendFormat": "iowait"
    },
    {
     "expr": "100 - (avg (irate(node_cpu_seconds_total{kubernetes_node=\"$Node\",mode=~\"idle\"}[5m])) * 100)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Node Memory Usage.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$Node\"}",
     "legendFormat": "total available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$Node\"} - (node_memory_MemFree_bytes{kubernetes_node=\"$Node\"} + node_memory_Cached_bytes{kubernetes_node=\"$Node\"} + node_memory_Buffers_bytes{kubernetes_node=\"$Node\"})",
     "legendFormat": "used"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{kubernetes_node=\"$Node\"} - node_memory_SwapFree_bytes{kubernetes_node=\"$Node\"})",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Node Network I/O",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{kubernetes_node=\"$Node\"}[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{kubernetes_node=\"$Node\"}[5m]))",
     "legendFormat": "transmitted"
    }
   ]
  },
  {
   "title": "Pods Using Most Node Memory",
   "type": "graph",
   "description": "Pods using the most memory on this node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(container_memory_working_set_bytes{kubernetes_io_hostname=\"$Node\",pod_name!=\"\"}) by (pod_name)))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods Using Most Node CPU",
   "type": "graph",
   "description": "Pods using the most CPU on this node.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum by (pod_name)( rate(container_cpu_usage_seconds_total{kubernetes_io_hostname=\"$Node\",pod_name!=\"\"}[5m] ) ))) * 100",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}