{
 "title": "EKS Cluster Overview",
 "description": "Summary metrics about containers running on Kubernetes nodes and mainline kubernetes statistics",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{label_eks_amazonaws_com_nodegroup=\"$nodegroup\"}, label_kubernetes_io_hostname)"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "nodegroup",
    "label": "Nodegroup",
    "query": "label_values(kube_node_labels{kubernetes_namespace=\"ops\"},label_eks_amazonaws_com_nodegroup)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes) - sum (node_filesystem_free_bytes)) / sum (node_filesystem_size_bytes)"
    },
    {}
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Node Uptime (All Nodes)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "node_time_seconds{kubernetes_namespace=\"ops\"} - node_boot_time_seconds{kubernetes_namespace=\"ops\"}",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Node Disk Usage (All Nodes)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{kubernetes_namespace=\"ops\",mountpoint=\"/\"} - node_filesystem_free_bytes{kubernetes_namespace=\"ops\",mountpoint=\"/\"}) / node_filesystem_size_bytes{kubernetes_namespace=\"ops\",mountpoint=\"/\"} * 100",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_nodegroup=\"$nodegroup\"})"
    }
   ]
  },
  { "title": "Resource Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (namespace)"
    },
    {
     "expr": "Sum(kube_pod_status_phase{phase=\"Unknown\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running) by (namespace)"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_waiting[5m])) by (namespace)"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_terminated[5m])) by (namespace)"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[15m])) by (namespace)"
    }
   ]
  }
 ]
}