{
 "title": "EKS Pod Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels,namespace)"
   },
   {
    "name": "pod_name",
    "label": "pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},pod)"
   },
   {
    "name": "container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod_name\"}, container)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\",pod=\"$pod_name\"},kubernetes_node)"
   },
   {
    "name": "pod_ip",
    "label": "Pod IP",
    "query": "label_values(kube_pod_info{pod=\"$pod_name\", kubernetes_node=\"$node\"}, pod_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod IP Address",
   "type": "text",
   "description": "IP Address used by the POD.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "content": "<h1><p style=\"text-align: center;\">$pod_ip</p></h1>\n\n\n\n",
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Memory Usage (Mb)",
   "type": "singlestat",
   "description": "Amount of RAM used by the Pod. Calculated from the sum of metric container_memory_working_set_bytes for all containers within the pod.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod_name\"}) / 1024 / 1000"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "singlestat",
   "description": "Current status of the pod.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod_name\", phase=\"Failed\"}*1) + scalar(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod_name\", phase=\"Pending\"}*2) + scalar(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod_name\", phase=\"Running\"}*3) + scalar(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod_name\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{namespace=\"$namespace\",pod=\"$pod_name\", phase=\"Unknown\"}*5)"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "singlestat",
   "description": "Number of times a pod container has restarted.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "Envoy - Upstream Clusters",
   "type": "singlestat",
   "description": "The number of active upstream Envoy clusters for this pod. ",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_cluster_manager_active_clusters{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$pod_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Network Failures",
   "type": "singlestat",
   "description": "Number of times a health-check has failed due to network failure.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_health_check_network_failure{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=\"$pod_name\",envoy_cluster_name=~\".*.main-collector.*.|.*.dr-collector.*.\"}[5m]))"
    }
   ]
  },
  {
   "title": "Envoy - Upstream Total Connections",
   "type": "graph",
   "description": "The number of connections upstream - i.e. hosts  receiving connections and requests from Envoy.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\".*collector.*\",kubernetes_pod_name=\"$pod_name\",kubernetes_namespace=\"$namespace\"}[5m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Cluster Downstream Connections",
   "type": "graph",
   "description": "The number of active downstream connections - i.e. hosts that connect to Envoy, send requests, and receive responses.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_downstream_cx_total{kubernetes_pod_name=\"$pod_name\",envoy_listener_address=~\".*.6514\",kubernetes_namespace=\"$namespace\"}[5m])) by (kubernetes_pod_name,envoy_listener_address)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "description": "Pod CPU Usage.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace=\"$namespace\",pod_name=\"$pod_name\"}[5m])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "description": "Pod Memory Usage.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",namespace=\"$namespace\",pod_name=\"$pod_name\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}