{{- if .Values.querier.enabled -}}
{{- if .Values.serviceAccounts.querier.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.querier.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.querier" . }}
{{- end }}
{{- end }}
