{{- if .Values.storegateway.enabled -}}
{{- if .Values.serviceAccounts.storegateway.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.storegateway.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.storegateway" . }}
{{- end }}
{{- end }}
